# Generated by Django 2.2.2 on 2019-06-16 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190616_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='uuid',
            field=models.CharField(default=uuid.uuid1, max_length=64, verbose_name='uuid'),
        ),
    ]
