# Generated by Django 2.2.2 on 2019-06-17 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=64, null=True, verbose_name='uuid'),
        ),
    ]
